name: Android CI Build

on:
  # Workflow akan berjalan setiap kali ada push atau Pull Request ke branch main.
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest # Menggunakan mesin virtual Linux (Ubuntu)

    steps:
    - name: Checkout Code
      # Mengunduh kode dari repositori
      uses: actions/checkout@v4

    - name: Set up JDK 17
      # Menyiapkan lingkungan Java Development Kit (JDK)
      uses: actions/setup-java@v4
      with:
        java-version: '17' # Versi Java yang direkomendasikan untuk Android
        distribution: 'temurin'
        cache: gradle

    - name: Grant Execute Permission for Gradle Wrapper
      # Memastikan skrip gradlew dapat dijalankan
      run: chmod +x gradlew

    - name: Build Debug APK
      # Menjalankan perintah Gradle untuk membuat APK debug
      run: ./gradlew assembleDebug

    - name: Upload Debug APK Artifact
      # Menyimpan hasil build (APK) sebagai 'artifact'
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
