# .github/workflows/android-build.yml

name: Build Android APK (Release)

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        name: Checkout Code

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Set up Android SDK
        # Menggunakan action setup-android yang minimal karena make.sh Anda sudah menangani tooling
        uses: android-actions/setup-android@v3 

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      # PERUBAHAN: Menggunakan 'build' untuk APK rilis yang ditandatangani
      - name: Build Release APK via make.sh
        run: ./make.sh build 

      - name: Upload Release APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          # Ganti 'appname' jika perlu, tapi 'make.sh build' menamai APK berdasarkan $appname
          path: ${{ github.workspace }}/app-release.apk
